### PR TITLE
feat(chainguard): add support for Chainguard distro

### PR DESCRIPTION
**Pull request by luhring**
Adds support for ingesting Chainguard's distro secdb for https://github.com/aquasecurity/trivy/issues/3630

### CODE REVIEW

**Comment by knqyf263** [comment]
PR looks good, but our repository storing security advisories may have broken GitHub. It always returns 500 in my environment. We cannot see the result of the chainguard secdb now...
https://github.com/aquasecurity/vuln-list/

I've contacted GitHub. Could you wait for a while?

**Comment by luhring** [comment]
@knqyf263 Sure thing, and thanks for looking at the PR. Good luck with GitHub!

Do you think we could plan to have the Chainguard distro support in for the [next Trivy release](https://github.com/aquasecurity/trivy/milestone/14)?

**Comment by patflynn** [comment]
hey there @knqyf263 , just checking-in to see if there's anything we can do to help land this PR.  Are you all still blocked on Github?  Any chance we can be expedited to make the next release? :pray:

**Comment by knqyf263** [comment]
>Are you all still blocked on Github?

Yes, they responded they are trying to fix it now.

>Any chance we can be expedited to make the next release?

It depends on GitHub.

**Comment by luhring** [comment]
Hi @knqyf263, just curious how it's going with GitHub. Any rays of hope?

**Comment by knqyf263** [comment]
Unfortunately, the situation is getting worse. GitHub API is unstable now. It is really critical for us and I reminded them several times, but their answer was always "under investigation"😢

**Comment by luhring** [comment]
That's terrible. Sorry to hear that! We're all rooting for you over here... 🤞

**Comment by knqyf263** [comment]
GitHub is back. Hopefully, we will merge the PR this month.

**Comment by luhring** [comment]
@knqyf263 Fantastic news! Let me know what you need from me regarding these PRs.

**Comment by knqyf263** [comment]
Hopefully, we'll include it in v0.39.0, which will be released at the end of this month. If we don't make it to v0.39.0, we will most likely release v0.40.0 around the middle of next month.

**Comment by luhring** [comment]
> Hopefully, we'll include it in v0.39.0, which will be released at the end of this month. If we don't make it to v0.39.0, we will most likely release v0.40.0 around the middle of next month.

Sounds great!

**Review by knqyf263 — APPROVED** [review]

**Comment by luhring** [comment]
Yay, thanks @knqyf263!! Looking forward to merging the corresponding trivy-db and trivy PRs! 🎉

**Pull request merged**
