### PR TITLE
fix: cve file name validation

### PR DESCRIPTION
**Pull request by chen-keinan**
Add cve file name validation when checking existing cves && dead code cleanup

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
The severity field is still wrong.

```
      "severity": [
        {
          "type": "CVSS_V3_0",
          "score": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
```

CVSS_V3_0 is undefined.
https://ossf.github.io/osv-schema/#severitytype-field

**Comment by knqyf263** [comment]
Can we fix this mistake as well?
https://github.com/aquasecurity/vuln-list-update/pull/239#discussion_r1338603680

**Comment by chen-keinan** [comment]
@knqyf263 both are fixed

**Comment by knqyf263** [comment]
LGTM. Please let me re-test this change tomorrow.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
I confirmed it worked with trivy-db.

**Comment by knqyf263** [comment]
BTW, the job is failing, but the shell script exits with 0. We probably need to add `-eu`, like `#!/bin/bash -eu`.
https://github.com/aquasecurity/vuln-list-update/blob/8d2a522b96f0d08db4ff697c79795e2d0676a250/create_pr.sh#L1

**Comment by knqyf263** [comment]
I'll update it.

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/vuln-list-update/pull/245

**Comment by knqyf263** [comment]
Do we still have a bug?
https://github.com/aquasecurity/vuln-list-k8s/pull/55#event-10495640403

**Pull request merged**
