### PR TITLE
chore(ci): parallelize update workflow

### LINKED ISSUE #101: refactor : Update vuln-list repo
The last workflow took 1h 27m 44s to pass and the longest step took 19m 28s.

What would you think of splitting this workflow in two step.
The first would build the vuln-list-update executable and upload it with actions/upload-artifact
The second would be a matrix of the differents targets (with their appropriate names) which would download the artifact (actions/download-artifact) and then execute `./vuln-list-update -target ...`

The advantage of matrix is of course parallelization of the tasks.
What I don't know yet to create the right PR is what needs to be know by each step (GITHUB_TOKEN, GITHUB_ENV...)

### PR DESCRIPTION
**Pull request by mmorel-35**
Hi @knqyf263, this is an attemps to shorten update workflow duration.

What do you think ?

Fixes #101 

NB: squash commits instead of merge

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
vuln-list-update pushes commits to vuln-list. If we do these updates in parallel, they will be conflicted.

**Comment by mmorel-35** [comment]
I see, so what it needs is a kind of map reduce system. The retrieving of the content is parallel but the persistence happens only once.

**Comment by knqyf263** [comment]
Exactly.

**Comment by mmorel-35** [comment]
Ok, so I drop this PR. It can be reopen when the projet is map reduce compatible.

**Pull request closed without merging**
